version: '3'
services:
  frontend:
    build:
      dockerfile: Dockerfile-dev
      context: .
    ports:
      - "3000:3000"
    volumes:
      - /opt/frontend-app/node_modules
      - .:/opt/frontend-app
  frontend-test:
    build:
      dockerfile: Dockerfile-dev
      context: .
    volumes:
      - /opt/frontend-app/node_modules
      - .:/opt/frontend-app
    command: ["npm", "run", "test"]
